CREATE DATABASE QLNS
GO 
USE QLNS
GO

CREATE TABLE ChucVu(
MaChucVu CHAR(10) PRIMARY KEY,
TenChucVu NVARCHAR(50)
)
GO

CREATE TABLE Luong(
BacLuong INT PRIMARY KEY,
LuongCoBan MONEY,
HeSoLuong INT,
HeSoPhuCap INT
)
GO

CREATE TABLE PhongBan(
MaPB CHAR(10) PRIMARY KEY,
TenPB NVARCHAR(50),
MaTruongPhong CHAR(10)
)
GO

CREATE TABLE TrinhDoHocVan(
MaTDHV CHAR(10) PRIMARY KEY,
TenTrinhDo NVARCHAR(50),
ChuyenNganh NVARCHAR(50)
)
GO

CREATE TABLE Taikhoan(
TenTK VARCHAR(50) PRIMARY KEY,
MatKhau VARCHAR(50),
LoaiTK INT 
)

CREATE TABLE NhanVien(
MaNV CHAR(10) PRIMARY KEY,
HoTen NVARCHAR(50),
DanToc NVARCHAR(50),
GioiTinh NVARCHAR(3) CHECK (GioiTinh IN (N'Nam',N'Nữ')),
SDT INT,
QueQuan NVARCHAR(50),
NgaySinh DATE,
MaTDHV CHAR(10) REFERENCES TrinhDoHocVan(MaTDHV),
MaPB CHAR(10) REFERENCES PhongBan(MaPB),
BacLuong INT REFERENCES Luong(BacLuong),
MaChucVu CHAR(10) REFERENCES ChucVu(MaChucVu),
TenTK VARCHAR(50) REFERENCES TaiKhoan(TenTK)
)
GO



